import Misal_Pav from '../assets/Misal Pav.jpg'
import Usal_Pav from '../assets/Usal Pav.jpg'
import Pohe from '../assets/Pohe.jpg'
import Shiraa from '../assets/Shiraa.jpg'
import Idli_Sambar from '../assets/Idli Sambar.jpg'
import Paneer_Masala from '../assets/Paneer Masala.jpg'
import Veg_Kolhapuri from '../assets/Veg Kolhapuri.jpg'
import Dal_Khichdi from '../assets/Dal Khichdi.jpg'
import Malwani_Chicken from '../assets/Malwani Chicken.jpg'
import Surmai_Fry from '../assets/Surmai Fry.jpg'
import Mutton_Thali from '../assets/Mutton Thali.jpg'
import Chicken_Thali from '../assets/Chicken Thali.jpg'
import Veg_Thali from '../assets/Veg Thali.jpg'
import Chicken_Biryani from '../assets/Chicken Biryani.jpg'
import Zhunka_Bhakar from '../assets/Zhunka Bhakar.jpg'
import Masala_Dosa from '../assets/Masala Dosa.jpg'
import Butter_Chicken from '../assets/Butter Chicken.jpg'
import Mutton_Curry from '../assets/Mutton Curry.jpg'
import Palak_Paneer from '../assets/Palak Paneer.jpg'
import Egg_Masala from '../assets/Egg Masala.jpg'
import Vada_Pav from '../assets/Vada Pav.jpg'

const images = [Egg_Masala,Vada_Pav,Palak_Paneer,Mutton_Curry,Butter_Chicken,Malwani_Chicken,Misal_Pav,Mutton_Thali,Usal_Pav,Paneer_Masala,Pohe,Shiraa,Idli_Sambar,Veg_Kolhapuri,Veg_Thali,Dal_Khichdi,Surmai_Fry,Chicken_Biryani,Chicken_Thali,Zhunka_Bhakar,Masala_Dosa]
export default images